baseURL = "/"
languageCode = "en-us"
title = "Red Banksia"
themesDir = "themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-164972545-1"
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/rblogo.png"
    standard  = "images/redbanksia2.png"
    alt = "Red Banksia"

  [params.homepage_meta_tags]
    meta_description = "Red Banksia invests in real estate generating significant returns through planning and development."
    meta_og_title = "Red Banksia"
    meta_og_type = "property"
    meta_og_url = "https://redbanksia.com"
#    meta_og_image =
    meta_og_description = "Red Banksia invests in real estate generating significant returns through planning and development."
#    meta_twitter_card =
#    meta_twitter_site =
#s    meta_twitter_creator =

[menu]
  # Main Menu
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/services/"
    weight = 2

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "What we do"
    url = "/what-we-do/"
    weight = 2

  [[menu.footer]]
    name = "Projects"
    url = "/services/"
    weight = 3

  [[menu.footer]]
    name = "Team"
    url = "/team/"
    weight = 4

  [[menu.footer]]
      name = "Investors"
      url = "/Investors/"
      weight = 5

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 6
